[api]
dev-api-0 ansible_host=91.98.230.85
dev-api-1 ansible_host=91.98.25.254

prod-api-0 ansible_host=178.104.101.143
prod-api-1 ansible_host=178.104.113.44

[db]
dev-db ansible_host=91.98.114.140
prod-db ansible_host=178.104.126.76

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
